//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.munsun.task2.model;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.jvnet.jaxb.lang.JAXBToStringStrategy;
import org.jvnet.jaxb.lang.ToString;
import org.jvnet.jaxb.lang.ToStringStrategy;
import org.jvnet.jaxb.locator.ObjectLocator;


/**
 * <p>Java class for PaymentScheduleElement complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="PaymentScheduleElement">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="numberPayment" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="paymentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="totalPayment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="interestPayment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="debtPayment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="remainingDebt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentScheduleElement", propOrder = {
    "numberPayment",
    "paymentDate",
    "totalPayment",
    "interestPayment",
    "debtPayment",
    "remainingDebt"
})
public class PaymentScheduleElement implements ToString
{

    protected int numberPayment;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paymentDate;
    @XmlElement(required = true)
    protected BigDecimal totalPayment;
    @XmlElement(required = true)
    protected BigDecimal interestPayment;
    @XmlElement(required = true)
    protected BigDecimal debtPayment;
    @XmlElement(required = true)
    protected BigDecimal remainingDebt;

    /**
     * Gets the value of the numberPayment property.
     * 
     */
    public int getNumberPayment() {
        return numberPayment;
    }

    /**
     * Sets the value of the numberPayment property.
     * 
     */
    public void setNumberPayment(int value) {
        this.numberPayment = value;
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentDate(XMLGregorianCalendar value) {
        this.paymentDate = value;
    }

    /**
     * Gets the value of the totalPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalPayment() {
        return totalPayment;
    }

    /**
     * Sets the value of the totalPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalPayment(BigDecimal value) {
        this.totalPayment = value;
    }

    /**
     * Gets the value of the interestPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestPayment() {
        return interestPayment;
    }

    /**
     * Sets the value of the interestPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestPayment(BigDecimal value) {
        this.interestPayment = value;
    }

    /**
     * Gets the value of the debtPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDebtPayment() {
        return debtPayment;
    }

    /**
     * Sets the value of the debtPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDebtPayment(BigDecimal value) {
        this.debtPayment = value;
    }

    /**
     * Gets the value of the remainingDebt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRemainingDebt() {
        return remainingDebt;
    }

    /**
     * Sets the value of the remainingDebt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRemainingDebt(BigDecimal value) {
        this.remainingDebt = value;
    }

    @Override
    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.getInstance();
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    @Override
    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    @Override
    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            int theNumberPayment;
            theNumberPayment = this.getNumberPayment();
            strategy.appendField(locator, this, "numberPayment", buffer, theNumberPayment, true);
        }
        {
            XMLGregorianCalendar thePaymentDate;
            thePaymentDate = this.getPaymentDate();
            strategy.appendField(locator, this, "paymentDate", buffer, thePaymentDate, (this.paymentDate!= null));
        }
        {
            BigDecimal theTotalPayment;
            theTotalPayment = this.getTotalPayment();
            strategy.appendField(locator, this, "totalPayment", buffer, theTotalPayment, (this.totalPayment!= null));
        }
        {
            BigDecimal theInterestPayment;
            theInterestPayment = this.getInterestPayment();
            strategy.appendField(locator, this, "interestPayment", buffer, theInterestPayment, (this.interestPayment!= null));
        }
        {
            BigDecimal theDebtPayment;
            theDebtPayment = this.getDebtPayment();
            strategy.appendField(locator, this, "debtPayment", buffer, theDebtPayment, (this.debtPayment!= null));
        }
        {
            BigDecimal theRemainingDebt;
            theRemainingDebt = this.getRemainingDebt();
            strategy.appendField(locator, this, "remainingDebt", buffer, theRemainingDebt, (this.remainingDebt!= null));
        }
        return buffer;
    }

}
